import: definition.yaml

concurrency:
  task:
    perturbed-kg-dev-step-wise: 3
  agent:
    azure: 3

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - azure
    task:
      - perturbed-kg-dev-step-wise

output: "outputs/{TIMESTAMP}"
